# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{openstackcompute}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dan Prince"]
  s.date = %q{2010-10-10}
  s.description = %q{API Binding for OpenStack Compute}
  s.email = %q{dan.prince@rackspace.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "COPYING",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/openstackcompute.rb",
     "lib/openstackcompute/authentication.rb",
     "lib/openstackcompute/connection.rb",
     "lib/openstackcompute/entity_manager.rb",
     "lib/openstackcompute/exception.rb",
     "lib/openstackcompute/flavor.rb",
     "lib/openstackcompute/image.rb",
     "lib/openstackcompute/server.rb",
     "lib/openstackcompute/shared_ip_group.rb",
     "openstackcompute.gemspec",
     "test/cloudservers_authentication_test.rb",
     "test/cloudservers_connection_test.rb",
     "test/cloudservers_exception_test.rb",
     "test/cloudservers_servers_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{https://launchpad.net/ruby-openstack-compute}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{OpenStack Compute Ruby API}
  s.test_files = [
    "test/cloudservers_connection_test.rb",
     "test/cloudservers_exception_test.rb",
     "test/cloudservers_servers_test.rb",
     "test/cloudservers_authentication_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, [">= 0"])
    else
      s.add_dependency(%q<json>, [">= 0"])
    end
  else
    s.add_dependency(%q<json>, [">= 0"])
  end
end

